// 日本のルール・マナー（しごと・くらし・まち）。外国人の働く人が、最初に知っておくと困らないこと。
// 法律の細かい手続きや判断は扱わない（そこは会社の担当者・役所・相談窓口へ）。日本語教師・支援担当の校閲待ち。
// 日常生活の主な場面ごとに分ける（MANNER_CATS）。
// point＝大事なこと（やさしい日本語）、why＝なぜか、q＝「こんなとき どうする？」の問題（choices の answer 番目が正解）
export const MANNER_CATS = [
  { id: "work", icon: "🏢", ja: "職場", en: "At work", vi: "Ở nơi làm việc" },
  { id: "home", icon: "🏠", ja: "住まい", en: "At home (apartment)", vi: "Nhà ở (chung cư)" },
  { id: "garbage", icon: "🗑️", ja: "ごみ", en: "Garbage", vi: "Rác" },
  { id: "road", icon: "🚲", ja: "自転車・道", en: "Bicycles and roads", vi: "Xe đạp và đường phố" },
  { id: "train", icon: "🚃", ja: "電車・バス", en: "Trains and buses", vi: "Tàu điện và xe buýt" },
  { id: "shop", icon: "🛒", ja: "買い物・飲食店", en: "Shops and restaurants", vi: "Mua sắm và nhà hàng" },
  { id: "hospital", icon: "🏥", ja: "病院", en: "Hospitals and clinics", vi: "Bệnh viện, phòng khám" },
  { id: "office", icon: "🏛️", ja: "役所・手続き", en: "City office and paperwork", vi: "Cơ quan hành chính, thủ tục" },
  { id: "bath", icon: "♨️", ja: "おふろ", en: "Baths", vi: "Nhà tắm" },
  { id: "emergency", icon: "🚨", ja: "地震・緊急", en: "Earthquakes and emergencies", vi: "Động đất và khẩn cấp" },
  { id: "words", icon: "💬", ja: "あいまいな ことば", en: "Words with two meanings", vi: "Từ có hai nghĩa" },
];

export const MANNERS = [
  // ── しごと ──
  { id: "m-time", cat: "work",
    title: { ja: "時間を 守る", en: "Be on time", vi: "Đúng giờ" },
    point: { ja: "仕事が 始まる 5〜10分 前に 着きます。遅れそうな ときは、始まる 前に 電話で 上司に 連絡します。",
      en: "Arrive 5–10 minutes before work starts. If you might be late, call your boss before work starts.",
      vi: "Đến trước giờ làm 5–10 phút. Nếu có thể bị muộn, hãy gọi điện cho cấp trên trước giờ bắt đầu." },
    why: { ja: "日本の 職場では、時間を 守る ことが 信頼に なります。連絡が あれば、仕事の 予定を 変えられます。",
      en: "In Japanese workplaces, being on time builds trust. If you call, the team can change the work plan.",
      vi: "Ở nơi làm việc Nhật, đúng giờ tạo nên sự tin tưởng. Nếu bạn báo trước, mọi người có thể đổi kế hoạch công việc." },
    q: { ja: "電車が 止まって、仕事に 遅れそうです。どう しますか。",
      choices: ["着いてから 謝る", "始まる 前に 電話で 上司に 連絡する", "友だちに 伝えて もらう"], answer: 1 } },
  { id: "m-absent", cat: "work",
    title: { ja: "休む ときの 連絡", en: "Calling in sick", vi: "Báo nghỉ" },
    point: { ja: "その日に 休む ときは、仕事が 始まる 前に 上司に 連絡します。電話か メッセージかは、会社の ルールに 合わせます。",
      en: "If you must take the day off, tell your boss before work starts. Follow your company's rule on phone or message.",
      vi: "Nếu phải nghỉ trong ngày, hãy báo cho cấp trên trước giờ làm. Gọi điện hay nhắn tin thì theo quy định của công ty." },
    why: { ja: "だれも 知らないと、みんなが 心配して、仕事の 人数も 足りなく なります。",
      en: "If no one knows, everyone worries and the team is short of people.",
      vi: "Nếu không ai biết, mọi người sẽ lo lắng và thiếu người làm." },
    q: { ja: "朝、熱が 出て 休みたいです。どう しますか。",
      choices: ["何も 言わないで 休む", "仕事が 始まる 前に 上司に 連絡する", "次の 日に 説明する"], answer: 1 } },
  { id: "m-hourensou", cat: "work",
    title: { ja: "報告・連絡・相談（ほうれんそう）", en: "Report, inform, consult (Hō-Ren-Sō)", vi: "Báo cáo – liên lạc – trao đổi (Hō-Ren-Sō)" },
    point: { ja: "終わったら 報告。変わった ことは 連絡。わからない ときや 困った ときは 相談します。",
      en: "Report when you finish. Inform when something changes. Consult when you don't understand or have a problem.",
      vi: "Làm xong thì báo cáo. Có thay đổi thì liên lạc. Không hiểu hoặc gặp khó khăn thì trao đổi." },
    why: { ja: "わかった ふりを すると、まちがいや 事故に なります。聞く ことは はずかしく ありません。",
      en: "Pretending to understand leads to mistakes and accidents. Asking is not embarrassing.",
      vi: "Giả vờ hiểu sẽ dẫn đến sai sót và tai nạn. Hỏi lại không có gì đáng xấu hổ." },
    q: { ja: "上司の 指示が よく わかりませんでした。どう しますか。",
      choices: ["わかった ふりを する", "すぐ 聞き返す", "自分の 考えで やる"], answer: 1 } },
  { id: "m-greet", cat: "work",
    title: { ja: "あいさつ", en: "Greetings", vi: "Chào hỏi" },
    point: { ja: "朝は「おはようございます」。先に 帰る ときは「お先に 失礼します」。残って いる 人には「お疲れさまです」。",
      en: "Morning: “Ohayō gozaimasu.” Leaving first: “Osaki ni shitsurei shimasu.” To people still working: “Otsukaresama desu.”",
      vi: "Buổi sáng: “Ohayō gozaimasu”. Về trước: “Osaki ni shitsurei shimasu”. Với người còn ở lại: “Otsukaresama desu”." },
    why: { ja: "あいさつは、仕事の 仲間との 関係を よく します。",
      en: "Greetings build good relationships with coworkers.",
      vi: "Chào hỏi giúp quan hệ với đồng nghiệp tốt hơn." },
    q: { ja: "仕事が 終わって、先に 帰ります。何と 言いますか。",
      choices: ["さようなら", "お先に 失礼します", "ばいばい"], answer: 1 } },
  { id: "m-mistake", cat: "work",
    title: { ja: "ミスを したら すぐ 報告", en: "Report mistakes right away", vi: "Mắc lỗi thì báo ngay" },
    point: { ja: "ミスや 事故は かくさないで、すぐ 上司に 言います。悪い ことほど 早く 報告します。",
      en: "Don't hide mistakes or accidents. Tell your boss right away. The worse the news, the sooner you report.",
      vi: "Không giấu lỗi hay sự cố, hãy báo cấp trên ngay. Tin càng xấu càng phải báo sớm." },
    why: { ja: "早く わかれば、大きな 問題に なる 前に 直せます。",
      en: "If found early, it can be fixed before it becomes a big problem.",
      vi: "Biết sớm thì có thể sửa trước khi thành vấn đề lớn." },
    q: { ja: "仕事中に 商品を 落として こわしました。どう しますか。",
      choices: ["だまって かたづける", "すぐ 上司に 報告する", "帰る 前に 言う"], answer: 1 } },
  { id: "m-grooming", cat: "work",
    title: { ja: "身だしなみ", en: "Neat appearance", vi: "Vệ sinh, trang phục" },
    point: { ja: "清潔な 服を 着て、かみ・つめ・においに 気を つけます。飲食や 介護の 仕事では、つめを 短く して、指輪などを 外します。",
      en: "Wear clean clothes and take care of your hair, nails and smell. In food service and care work, keep nails short and remove rings.",
      vi: "Mặc quần áo sạch, chú ý tóc, móng tay và mùi cơ thể. Làm nhà hàng hay chăm sóc thì cắt móng ngắn, tháo nhẫn." },
    why: { ja: "食べ物や 人の 体に さわる 仕事では、清潔さが 安全に つながります。",
      en: "When you touch food or people's bodies, cleanliness means safety.",
      vi: "Khi tiếp xúc với đồ ăn hay cơ thể người khác, sạch sẽ là an toàn." },
    q: { ja: "飲食店で 働きます。正しいのは どれですか。",
      choices: ["つめを 長く して おく", "指輪を つけた まま 料理する", "つめを 短く して、手を よく 洗う"], answer: 2 } },
  { id: "m-safety", cat: "work",
    title: { ja: "安全の ルール", en: "Safety rules", vi: "Quy định an toàn" },
    point: { ja: "ヘルメット・安全靴・手袋など、決められた ものは 必ず 使います。あぶないと 思ったら、止めて 報告します。",
      en: "Always use the required gear such as helmets, safety shoes and gloves. If something seems dangerous, stop and report it.",
      vi: "Luôn dùng đồ bảo hộ quy định như mũ, giày bảo hộ, găng tay. Thấy nguy hiểm thì dừng lại và báo cáo." },
    why: { ja: "けがは 自分も 家族も 困ります。「少しだけ」が 大きな 事故に なります。",
      en: "An injury hurts you and your family. “Just a little” can become a big accident.",
      vi: "Bị thương thì cả bạn và gia đình đều khổ. “Một chút thôi” có thể thành tai nạn lớn." },
    q: { ja: "暑いので ヘルメットを 外したいです。どう しますか。",
      choices: ["少しなら 外す", "必ず かぶる。つらい ときは 上司に 相談する", "休けいの あとだけ かぶる"], answer: 1 } },
  { id: "m-secret", cat: "work",
    title: { ja: "会社や お客様の 情報", en: "Company and customer information", vi: "Thông tin công ty và khách hàng" },
    point: { ja: "会社や お客様・利用者の ことは、外で 話しません。職場の 写真を 許可なく SNSに のせません。",
      en: "Don't talk about the company, customers or care users outside work. Don't post workplace photos on social media without permission.",
      vi: "Không nói chuyện về công ty, khách hàng hay người được chăm sóc ở bên ngoài. Không đăng ảnh nơi làm việc lên mạng khi chưa được phép." },
    why: { ja: "情報が 外に 出ると、お客様や 会社が 困り、あなたも 責任を 問われます。",
      en: "Leaked information harms customers and the company, and you can be held responsible.",
      vi: "Thông tin bị lộ ra ngoài sẽ gây hại cho khách và công ty, và bạn cũng phải chịu trách nhiệm." },
    q: { ja: "職場で 写真を とりました。SNSに のせても いいですか。",
      choices: ["友だちだけに 見せるなら いい", "許可なく のせない", "顔が 写って いなければ いい"], answer: 1 } },
  { id: "m-5s", cat: "work",
    title: { ja: "整理・整とん", en: "Keep things in order", vi: "Sắp xếp gọn gàng" },
    point: { ja: "使った 道具は、決まった 場所に もどします。いらない ものは すてて、通る ところに ものを 置きません。",
      en: "Return tools to their places. Throw away what you don't need, and don't leave things in walkways.",
      vi: "Dụng cụ dùng xong thì để lại đúng chỗ. Vứt bỏ đồ không cần, không để đồ ở lối đi." },
    why: { ja: "さがす 時間が へり、つまずく 事故も ふせげます。",
      en: "It saves time searching and prevents tripping accidents.",
      vi: "Đỡ mất thời gian tìm kiếm và tránh vấp ngã." },
    q: { ja: "道具を 使い 終わりました。どう しますか。",
      choices: ["近くに 置いて おく", "決まった 場所に もどす", "かばんに 入れて おく"], answer: 1 } },
  { id: "m-phone", cat: "work",
    title: { ja: "仕事中の スマホ", en: "Phones during work", vi: "Điện thoại trong giờ làm" },
    point: { ja: "仕事中は スマホを 使いません。休けい時間に 使います。急ぎの ときは 上司に 言ってから 使います。",
      en: "Don't use your phone while working. Use it on breaks. If it's urgent, ask your boss first.",
      vi: "Không dùng điện thoại khi đang làm. Dùng vào giờ nghỉ. Nếu gấp, hãy nói với cấp trên trước." },
    why: { ja: "仕事に 集中できず、ミスや 事故の もとに なります。",
      en: "You can't focus, which leads to mistakes and accidents.",
      vi: "Không tập trung được, dễ gây sai sót và tai nạn." },
    q: { ja: "仕事中に 家族から メッセージが 来ました。どう しますか。",
      choices: ["すぐ 返事を 書く", "休けい時間に 見る。急ぎなら 上司に 言う", "トイレで こっそり 見る"], answer: 1 } },
  { id: "m-overtime", cat: "work",
    title: { ja: "残業と 休けい", en: "Overtime and breaks", vi: "Làm thêm giờ và nghỉ giải lao" },
    point: { ja: "残業は 上司の 指示が ある ときに します。時間内に 終わらない ときは、早めに 相談します。",
      en: "Work overtime only when your boss tells you to. If you can't finish in time, talk to your boss early.",
      vi: "Chỉ làm thêm giờ khi cấp trên yêu cầu. Nếu không xong kịp, hãy trao đổi sớm." },
    why: { ja: "働いた 時間は、会社が 正しく 記録して 給料を 払う 決まりが あります。",
      en: "The company must record your working hours correctly and pay for them.",
      vi: "Công ty phải ghi chép đúng giờ làm và trả lương cho bạn." },
    q: { ja: "仕事が 時間内に 終わりそうに ありません。どう しますか。",
      choices: ["だまって 残って 働く", "早めに 上司に 相談する", "残りは 次の 人に まかせて 帰る"], answer: 1 } },
  { id: "m-payslip", cat: "work",
    title: { ja: "給料明細を 見る", en: "Check your payslip", vi: "Xem phiếu lương" },
    point: { ja: "給料明細を もらったら、働いた 時間や 引かれた お金を 見ます。わからない ことは 会社の 担当者に 聞きます。",
      en: "When you get your payslip, check your hours and deductions. Ask the person in charge if anything is unclear.",
      vi: "Khi nhận phiếu lương, hãy xem giờ làm và các khoản bị trừ. Không hiểu thì hỏi người phụ trách ở công ty." },
    why: { ja: "税金や 保険などが 引かれます。おかしいと 思ったら、早く 聞く ほうが いいです。",
      en: "Taxes and insurance are deducted. If something seems wrong, ask early.",
      vi: "Thuế và bảo hiểm sẽ bị trừ. Thấy lạ thì nên hỏi sớm." },
    q: { ja: "給料明細で、わからない お金が 引かれて います。どう しますか。",
      choices: ["そのままに する", "会社の 担当者に 聞く", "SNSで 文句を 書く"], answer: 1 } },

  // ── くらし ──
  { id: "m-garbage", cat: "garbage",
    title: { ja: "ごみの 出し方", en: "Putting out garbage", vi: "Cách bỏ rác" },
    point: { ja: "ごみは 種類ごとに 分けて、決まった 日の 朝に、決まった 場所に 出します。ルールは 市や 町に よって 違います。",
      en: "Sort garbage by type and put it out on the set day, in the morning, at the set place. Rules differ by city.",
      vi: "Phân loại rác và bỏ vào buổi sáng đúng ngày, đúng chỗ quy định. Quy định khác nhau tùy thành phố." },
    why: { ja: "日を まちがえると、ごみが 残って 近所の 人が 困ります。",
      en: "If you get the day wrong, the garbage stays and the neighbors are bothered.",
      vi: "Bỏ sai ngày thì rác bị để lại, làm phiền hàng xóm." },
    q: { ja: "ごみは いつ 出しますか。",
      choices: ["いつでも いい", "決まった 日の 朝", "前の 日の 夜 おそく"], answer: 1 } },
  { id: "m-noise", cat: "home",
    title: { ja: "夜の 音", en: "Noise at night", vi: "Tiếng ồn ban đêm" },
    point: { ja: "アパートでは、夜（だいたい 10時より あと）は 大きな 声や 音楽、洗たく機の 音に 気を つけます。",
      en: "In apartments, be careful with loud voices, music and washing machines at night (roughly after 10 p.m.).",
      vi: "Ở chung cư, ban đêm (khoảng sau 10 giờ) hãy chú ý không nói to, mở nhạc lớn hay chạy máy giặt." },
    why: { ja: "日本の アパートは かべが うすい ことが 多く、となりに よく 聞こえます。",
      en: "Walls in Japanese apartments are often thin, so neighbors can hear.",
      vi: "Tường chung cư ở Nhật thường mỏng nên hàng xóm nghe rõ." },
    q: { ja: "夜 11時に 友だちと 部屋で 話して います。どう しますか。",
      choices: ["大きな 声で 歌う", "小さな 声で 話す", "まどを 開けて 話す"], answer: 1 } },
  { id: "m-bicycle", cat: "road",
    title: { ja: "自転車の ルール", en: "Bicycle rules", vi: "Quy định khi đi xe đạp" },
    point: { ja: "自転車は 車道の 左側を 走るのが 基本です。夜は ライトを つけます。二人乗り・かさを さしながら・スマホを 見ながらは だめです。",
      en: "Bicycles basically ride on the left side of the road. Use a light at night. No riding double, holding an umbrella, or looking at your phone.",
      vi: "Xe đạp về cơ bản đi bên trái lòng đường. Ban đêm bật đèn. Không chở hai người, không vừa đi vừa che ô hay xem điện thoại." },
    why: { ja: "自転車も 車の なかまです。ルールを 守らないと、事故や 罰金に なる ことが あります。",
      en: "Bicycles count as vehicles. Breaking rules can cause accidents or fines.",
      vi: "Xe đạp cũng được coi là phương tiện giao thông. Vi phạm có thể gây tai nạn hoặc bị phạt." },
    q: { ja: "雨の 日に 自転車に 乗ります。正しいのは どれですか。",
      choices: ["かさを さして 乗る", "レインコートを 着て 乗る", "スマホで 道を 見ながら 乗る"], answer: 1 } },
  { id: "m-train", cat: "train",
    title: { ja: "電車・バスの マナー", en: "Train and bus manners", vi: "Phép lịch sự trên tàu, xe buýt" },
    point: { ja: "並んで 待ち、降りる 人が 先です。車内では 電話で 話しません。お年よりや 体の 不自由な 人には 席を ゆずります。",
      en: "Line up and let people get off first. Don't talk on the phone inside. Give your seat to elderly or disabled people.",
      vi: "Xếp hàng chờ, để người xuống trước. Không nói chuyện điện thoại trên tàu xe. Nhường ghế cho người già, người khuyết tật." },
    why: { ja: "電車の 中は 静かに する ことが 多いです。みんなが 気持ちよく 乗る ためです。",
      en: "People usually keep quiet on trains so everyone can ride comfortably.",
      vi: "Trên tàu mọi người thường giữ yên lặng để ai cũng đi thoải mái." },
    q: { ja: "電車の 中で 電話が かかって きました。どう しますか。",
      choices: ["大きな 声で 話す", "出ないで、降りてから かけなおす", "スピーカーに して 話す"], answer: 1 } },
  { id: "m-bath", cat: "bath",
    title: { ja: "おふろ（銭湯・温泉）", en: "Public baths (sentō, onsen)", vi: "Nhà tắm công cộng (sentō, onsen)" },
    point: { ja: "おふろに 入る 前に 体を 洗います。タオルは お湯に 入れません。",
      en: "Wash your body before getting into the bath. Don't put your towel in the water.",
      vi: "Tắm rửa sạch trước khi vào bồn. Không cho khăn vào nước." },
    why: { ja: "お湯は みんなで 使うので、きれいに 使います。",
      en: "Everyone shares the water, so keep it clean.",
      vi: "Nước dùng chung nên phải giữ sạch." },
    q: { ja: "銭湯に 来ました。最初に 何を しますか。",
      choices: ["すぐ お湯に 入る", "体を 洗う", "タオルを お湯に 入れる"], answer: 1 } },
  { id: "m-shoes", cat: "home",
    title: { ja: "家に 入る ときは くつを ぬぐ", en: "Take off shoes indoors", vi: "Cởi giày khi vào nhà" },
    point: { ja: "家や 部屋に 入る ときは、げんかんで くつを ぬぎます。病院や 職場でも、スリッパに はきかえる ところが あります。",
      en: "Take off your shoes at the entrance when entering a home. Some hospitals and workplaces also ask you to change into slippers.",
      vi: "Cởi giày ở lối vào khi vào nhà. Một số bệnh viện, nơi làm việc cũng yêu cầu đổi sang dép." },
    why: { ja: "日本では、部屋の 床に すわったり ねたり するので、きれいに します。",
      en: "In Japan people sit and sleep on the floor, so it's kept clean.",
      vi: "Ở Nhật, người ta ngồi và ngủ trên sàn nên giữ sàn sạch." },
    q: { ja: "日本人の 友だちの 家に 行きました。どう しますか。",
      choices: ["くつの まま 入る", "げんかんで くつを ぬぐ", "部屋の 中で ぬぐ"], answer: 1 } },
  { id: "m-move", cat: "office",
    title: { ja: "引っこしの とどけ", en: "Report when you move", vi: "Báo khi chuyển nhà" },
    point: { ja: "引っこしたら、14日 以内に 新しい 市や 町の 役所で とどけを 出します。在留カードを 持って 行きます。",
      en: "After moving, report to the city office of your new area within 14 days. Bring your residence card.",
      vi: "Sau khi chuyển nhà, hãy khai báo ở tòa hành chính nơi ở mới trong vòng 14 ngày. Mang theo thẻ cư trú." },
    why: { ja: "住所が 変わった ことを 届けないと、大事な 手紙が とどかず、手続きで 困る ことが あります。くわしくは 会社の 担当者に 聞きましょう。",
      en: "If you don't report it, important letters won't reach you and procedures can become difficult. Ask the person in charge at your company for details.",
      vi: "Nếu không khai báo, thư quan trọng sẽ không đến và thủ tục có thể gặp rắc rối. Hãy hỏi người phụ trách ở công ty để biết chi tiết." },
    q: { ja: "引っこしました。役所に いつまでに 行きますか。",
      choices: ["1年 以内", "14日 以内", "行かなくて いい"], answer: 1 } },
  { id: "m-card", cat: "office",
    title: { ja: "在留カードは いつも 持つ", en: "Always carry your residence card", vi: "Luôn mang theo thẻ cư trú" },
    point: { ja: "在留カードは、出かける ときも いつも 持って いきます。なくしたら すぐ 会社の 担当者に 相談します。",
      en: "Always carry your residence card when you go out. If you lose it, tell the person in charge at your company right away.",
      vi: "Luôn mang thẻ cư trú khi ra ngoài. Nếu làm mất, hãy báo ngay cho người phụ trách ở công ty." },
    why: { ja: "持って いる ことが 決まりで、警察官などに 見せるよう 言われる ことが あります。",
      en: "Carrying it is required, and police may ask to see it.",
      vi: "Mang theo thẻ là quy định, cảnh sát có thể yêu cầu xuất trình." },
    q: { ja: "近くの コンビニに 行きます。在留カードは どう しますか。",
      choices: ["家に 置いて いく", "持って いく", "コピーを 持って いく"], answer: 1 } },

  // ── まち ──
  { id: "m-emergency", cat: "emergency",
    title: { ja: "こまった ときの 電話", en: "Emergency numbers", vi: "Số điện thoại khẩn cấp" },
    point: { ja: "事件や 事故は 110（警察）。火事や 急な 病気・大きな けがは 119（消防・救急車）。",
      en: "Crime or traffic accidents: 110 (police). Fire, sudden illness or serious injury: 119 (fire / ambulance).",
      vi: "Tội phạm, tai nạn: 110 (cảnh sát). Hỏa hoạn, bệnh đột ngột, bị thương nặng: 119 (cứu hỏa, xe cấp cứu)." },
    why: { ja: "あわてて 番号を まちがえないように、先に おぼえて おきます。",
      en: "Learn them now so you don't panic and dial the wrong number.",
      vi: "Hãy nhớ trước để không hoảng hốt bấm nhầm số." },
    q: { ja: "家の 近くで 火事を 見ました。何番に 電話しますか。",
      choices: ["110", "119", "117"], answer: 1 } },
  { id: "m-quake", cat: "emergency",
    title: { ja: "地震の とき", en: "During an earthquake", vi: "Khi có động đất" },
    point: { ja: "ゆれたら、つくえの 下などで 頭を 守ります。ゆれが おさまってから 外に 出ます。住んで いる ところの ひなん場所を 調べて おきます。",
      en: "When it shakes, protect your head under a desk. Go outside only after the shaking stops. Check your local evacuation site in advance.",
      vi: "Khi rung, hãy bảo vệ đầu dưới gầm bàn. Chỉ ra ngoài khi hết rung. Tìm hiểu trước nơi sơ tán gần nhà." },
    why: { ja: "ゆれて いる ときに 外へ 走ると、落ちて くる もので けがを します。",
      en: "Running outside while it's shaking can get you hurt by falling objects.",
      vi: "Chạy ra ngoài khi đang rung dễ bị thương do đồ vật rơi." },
    q: { ja: "部屋に いる とき、大きく ゆれました。最初に どう しますか。",
      choices: ["すぐ 外に 走る", "つくえの 下で 頭を 守る", "エレベーターで 下に 行く"], answer: 1 } },
  { id: "m-alcohol", cat: "shop",
    title: { ja: "お酒と たばこ", en: "Alcohol and tobacco", vi: "Rượu bia và thuốc lá" },
    point: { ja: "お酒と たばこは 20才から です。お酒を 飲んだら、車も 自転車も 運転しません。たばこは 決められた 場所で すいます。",
      en: "Alcohol and tobacco are allowed from age 20. After drinking, never drive a car or ride a bicycle. Smoke only in designated areas.",
      vi: "Rượu bia và thuốc lá từ 20 tuổi. Đã uống rượu thì không lái ô tô, không đi xe đạp. Chỉ hút thuốc ở nơi quy định." },
    why: { ja: "飲んで 運転するのは 法律で 禁止されて いて、大きな 事故に なります。",
      en: "Drunk driving is illegal and causes serious accidents.",
      vi: "Lái xe sau khi uống rượu bị pháp luật cấm và gây tai nạn nghiêm trọng." },
    q: { ja: "会社の 飲み会の あと、家に 帰ります。正しいのは どれですか。",
      choices: ["自転車で 帰る", "電車か 歩いて 帰る", "少しなら 車で 帰る"], answer: 1 } },
  { id: "m-line", cat: "shop",
    title: { ja: "順番を 守る", en: "Wait your turn", vi: "Giữ trật tự, xếp hàng" },
    point: { ja: "店や 駅では 列に 並んで、順番を 待ちます。",
      en: "Line up and wait your turn in shops and stations.",
      vi: "Ở cửa hàng và nhà ga, hãy xếp hàng và chờ đến lượt." },
    why: { ja: "日本では、列に 割りこむ ことは とても 失礼だと 思われます。",
      en: "In Japan, cutting in line is seen as very rude.",
      vi: "Ở Nhật, chen hàng bị coi là rất bất lịch sự." },
    q: { ja: "レジに 人が 並んで います。どう しますか。",
      choices: ["前に 入る", "列の 後ろに 並ぶ", "店員を 大きな 声で 呼ぶ"], answer: 1 } },
  { id: "m-hospital", cat: "hospital",
    title: { ja: "病院に 行く とき", en: "Going to a clinic", vi: "Khi đi bệnh viện" },
    point: { ja: "健康保険の 証明（マイナンバーカードなど）を 持って いきます。受付で 症状を 伝えます。わからない ことは 会社の 担当者に 相談します。",
      en: "Bring proof of health insurance (such as your My Number Card). Tell the reception your symptoms. Ask the person in charge at your company if unsure.",
      vi: "Mang theo giấy tờ chứng minh bảo hiểm y tế (như thẻ My Number). Nói triệu chứng ở quầy lễ tân. Không rõ thì hỏi người phụ trách ở công ty." },
    why: { ja: "保険の 証明が ないと、お金が 多く かかる ことが あります。",
      en: "Without proof of insurance, you may have to pay much more.",
      vi: "Không có giấy tờ bảo hiểm thì có thể phải trả nhiều tiền hơn." },
    q: { ja: "病院に 行きます。何を 持って いきますか。",
      choices: ["何も いらない", "健康保険の 証明（マイナンバーカードなど）", "パスポートだけ"], answer: 1 } },
  // ── 場面ごとに足したもの ──
  { id: "m-common", cat: "home",
    title: { ja: "ろうか・ベランダに ものを 置かない", en: "Keep hallways and balconies clear", vi: "Không để đồ ở hành lang, ban công" },
    point: { ja: "アパートの ろうかや 階段、ベランダの ひなんする ところには、ものを 置きません。",
      en: "Don't leave things in apartment hallways, stairs, or the evacuation area of the balcony.",
      vi: "Không để đồ ở hành lang, cầu thang hay lối thoát hiểm ở ban công chung cư." },
    why: { ja: "火事や 地震の とき、にげる 道が ふさがって あぶないからです。",
      en: "In a fire or earthquake, blocked paths make escape dangerous.",
      vi: "Khi cháy hay động đất, lối đi bị chắn sẽ rất nguy hiểm." },
    q: { ja: "部屋が せまいので、自転車を どこに 置きますか。",
      choices: ["アパートの ろうか", "決められた 自転車置き場", "階段の 下"], answer: 1 } },
  { id: "m-bulky", cat: "garbage",
    title: { ja: "大きい ごみ（粗大ごみ）", en: "Large items (oversized garbage)", vi: "Rác cỡ lớn" },
    point: { ja: "ふとんや 家具など 大きい ごみは、市や 町に 申しこんで、決まった 方法で 出します。お金が かかる ことが あります。",
      en: "For large items like futons and furniture, apply to the city and follow its method. There may be a fee.",
      vi: "Đồ lớn như chăn nệm, đồ nội thất phải đăng ký với thành phố và bỏ theo cách quy định. Có thể mất phí." },
    why: { ja: "ふつうの ごみの 日に 出しても、持って いって もらえません。",
      en: "They won't be collected on regular garbage days.",
      vi: "Bỏ vào ngày rác thường sẽ không được thu gom." },
    q: { ja: "古い いすを すてたいです。どう しますか。",
      choices: ["ふつうの ごみの 日に 出す", "市や 町に 申しこむ", "夜に 公園に 置く"], answer: 1 } },
  { id: "m-walk", cat: "road",
    title: { ja: "信号と 横断歩道", en: "Traffic lights and crosswalks", vi: "Đèn giao thông và vạch qua đường" },
    point: { ja: "道を わたる ときは、信号を 守って 横断歩道を わたります。赤の ときは、車が 来なくても 待ちます。",
      en: "Cross at crosswalks and follow the lights. Wait at red even if no cars are coming.",
      vi: "Qua đường ở vạch dành cho người đi bộ và theo đèn. Đèn đỏ thì chờ dù không có xe." },
    why: { ja: "日本の 車は 左側を 走ります。国と 違うので、よく 見て わたります。",
      en: "Cars in Japan drive on the left, which may differ from your country, so look carefully.",
      vi: "Ở Nhật xe chạy bên trái, có thể khác nước bạn, nên hãy quan sát kỹ." },
    q: { ja: "信号が 赤です。車は 来て いません。どう しますか。",
      choices: ["走って わたる", "青に なるまで 待つ", "横断歩道の ない ところで わたる"], answer: 1 } },
  { id: "m-tip", cat: "shop",
    title: { ja: "チップは いらない", en: "No tipping", vi: "Không cần tiền tip" },
    point: { ja: "日本の 店や レストランでは、チップは いりません。おつりは 受け取ります。",
      en: "No tips are needed at shops and restaurants in Japan. Take your change.",
      vi: "Ở cửa hàng, nhà hàng Nhật không cần tip. Hãy nhận lại tiền thừa." },
    why: { ja: "サービスの お金は、ねだんに 入って います。",
      en: "Service is included in the price.",
      vi: "Tiền dịch vụ đã nằm trong giá." },
    q: { ja: "レストランで おつりを もらいました。どう しますか。",
      choices: ["テーブルに 置いて いく", "そのまま 受け取る", "店員に 返す"], answer: 1 } },
  { id: "m-goods", cat: "shop",
    title: { ja: "買う 前の 商品", en: "Items before you pay", vi: "Hàng chưa trả tiền" },
    point: { ja: "お金を はらう 前に、店の 商品を 開けたり 食べたり しません。",
      en: "Don't open or eat items before paying for them.",
      vi: "Không mở hay ăn hàng của cửa hàng trước khi trả tiền." },
    why: { ja: "はらう 前に 食べると、どろぼうと 思われる ことが あります。",
      en: "Eating before paying can be treated as theft.",
      vi: "Ăn trước khi trả tiền có thể bị coi là ăn cắp." },
    q: { ja: "のどが かわきました。店の 飲み物を いつ 飲みますか。",
      choices: ["レジに 行く 前に 飲む", "お金を はらってから 飲む", "半分だけ 飲んで 返す"], answer: 1 } },
  { id: "m-medicine", cat: "hospital",
    title: { ja: "薬の 飲み方", en: "Taking medicine", vi: "Cách uống thuốc" },
    point: { ja: "薬は、医者や 薬剤師の 説明どおりに 飲みます。わからない ときは 薬局で 聞きます。人の 薬は 飲みません。",
      en: "Take medicine as the doctor or pharmacist told you. Ask at the pharmacy if unsure. Don't take other people's medicine.",
      vi: "Uống thuốc theo hướng dẫn của bác sĩ hoặc dược sĩ. Không rõ thì hỏi ở nhà thuốc. Không uống thuốc của người khác." },
    why: { ja: "飲む 量や 時間を まちがえると、体に 悪い ことが あります。",
      en: "The wrong amount or timing can harm your health.",
      vi: "Uống sai lượng hay sai giờ có thể có hại cho sức khỏe." },
    q: { ja: "薬の 飲み方が わかりません。どう しますか。",
      choices: ["友だちの 薬と 同じに 飲む", "薬局や 病院で 聞く", "たくさん 飲む"], answer: 1 } },
  // ── あいまいな ことば（いい意味にも ことわりにも 取れる、日本語に よく ある 言葉） ──
  { id: "w-daijoubu", cat: "words",
    title: { ja: "「大丈夫です」", en: "“Daijōbu desu”", vi: "“Daijōbu desu”" },
    point: { ja: "① 問題ない・元気です。② いりません（ことわり）。",
      en: "(1) No problem / I'm fine. (2) No thank you (a refusal).",
      vi: "(1) Không sao / Tôi ổn. (2) Không cần đâu (từ chối)." },
    why: { ja: "「〜は いりますか」「〜しましょうか」の 答えなら、たいてい「いりません」の 意味です。",
      en: "As an answer to “Do you need…?” or “Shall I…?”, it usually means “No, thank you.”",
      vi: "Nếu là câu trả lời cho “Có cần … không?” hay “Để tôi … nhé?” thì thường có nghĩa là “Không cần”." },
    q: { ja: "コンビニで「ふくろは いりますか」と 聞いたら、お客様が「大丈夫です」と 言いました。どういう 意味ですか。",
      choices: ["ふくろが ほしい", "ふくろは いらない", "体が 元気だ"], answer: 1 } },
  { id: "w-kekkou", cat: "words",
    title: { ja: "「結構です」", en: "“Kekkō desu”", vi: "“Kekkō desu”" },
    point: { ja: "① いりません・もう いいです（ことわり）。② それで いいです（OK）。",
      en: "(1) No thank you / That's enough (refusal). (2) That's fine (OK).",
      vi: "(1) Không cần / Đủ rồi (từ chối). (2) Như vậy là được (OK)." },
    why: { ja: "「いえ、結構です」「もう 結構です」は ことわり。「それで 結構です」は OK です。「けっこう むずかしい」の「けっこう」は「かなり」の 意味です。",
      en: "“Ie, kekkō desu” and “Mō kekkō desu” are refusals. “Sore de kekkō desu” means OK. “Kekkō muzukashii” means “quite difficult”.",
      vi: "“Ie, kekkō desu”, “Mō kekkō desu” là từ chối. “Sore de kekkō desu” là OK. “Kekkō muzukashii” nghĩa là “khá khó”." },
    q: { ja: "お客様に「お茶を もう 一ぱい いかがですか」と 聞いたら、「いえ、結構です」と 言われました。どう しますか。",
      choices: ["お茶を 入れる", "お茶は 入れない", "もっと 大きい カップに する"], answer: 1 } },
  { id: "w-iidesu", cat: "words",
    title: { ja: "「いいです」", en: "“Ii desu”", vi: "“Ii desu”" },
    point: { ja: "① いいです（OK・ほしい）。② いりません（ことわり）。",
      en: "(1) Good / OK / Yes please. (2) No thank you (refusal).",
      vi: "(1) Được / OK / Vâng. (2) Không cần (từ chối)." },
    why: { ja: "手を 横に ふって「いいです、いいです」と 言うのは ことわりです。わからない ときは「〜しても いいですか」と もう 一度 聞きます。",
      en: "Waving a hand while saying “Ii desu, ii desu” is a refusal. If unsure, ask again: “Is it OK if I…?”",
      vi: "Vừa xua tay vừa nói “Ii desu, ii desu” là từ chối. Không chắc thì hỏi lại: “Tôi làm … có được không?”" },
    q: { ja: "先輩の 荷物を 持とうと したら、手を ふって「いいです、いいです」と 言われました。どういう 意味ですか。",
      choices: ["持って ほしい", "持たなくて いい", "早く 持って"], answer: 1 } },
  { id: "w-sumimasen", cat: "words",
    title: { ja: "「すみません」", en: "“Sumimasen”", vi: "“Sumimasen”" },
    point: { ja: "① ごめんなさい。② 人を よぶ（すみません、ちょっと）。③ ありがとう。",
      en: "(1) I'm sorry. (2) Excuse me (to call someone). (3) Thank you.",
      vi: "(1) Xin lỗi. (2) Xin phép, cho hỏi (gọi người). (3) Cảm ơn." },
    why: { ja: "何か して もらった ときの「すみません」は「ありがとう」の 気持ちです。",
      en: "“Sumimasen” after someone does something for you means “thank you”.",
      vi: "“Sumimasen” khi được người khác giúp có nghĩa là “cảm ơn”." },
    q: { ja: "落とした ハンカチを 拾って わたしたら、相手が「あ、すみません」と 言いました。どういう 気持ちですか。",
      choices: ["おこって いる", "ありがとう", "よんで いる"], answer: 1 } },
  { id: "w-chotto", cat: "words",
    title: { ja: "「ちょっと…」", en: "“Chotto…”", vi: "“Chotto…”" },
    point: { ja: "① 少し。② 言いにくい ことわり（最後まで 言わない）。",
      en: "(1) A little. (2) A soft refusal (the sentence is left unfinished).",
      vi: "(1) Một chút. (2) Lời từ chối khó nói (không nói hết câu)." },
    why: { ja: "「明日は ちょっと…」と 文が 終わらない ときは、「できない」の 意味です。もう 一度 さそったり、理由を 聞いたり しません。",
      en: "When the sentence trails off, like “Ashita wa chotto…”, it means “I can't”. Don't push or ask why.",
      vi: "Khi câu bị bỏ lửng như “Ashita wa chotto…” thì nghĩa là “không được”. Đừng rủ lại hay hỏi lý do." },
    q: { ja: "「明日の 夜、食事に 行きませんか」と さそったら、「明日は ちょっと…」と 言われました。どういう 意味ですか。",
      choices: ["少しだけ 行く", "行けない", "あとで 返事を する"], answer: 1 } },
  { id: "w-kentou", cat: "words",
    title: { ja: "「考えておきます」「検討します」", en: "“Kangaete okimasu” / “Kentō shimasu”", vi: "“Kangaete okimasu” / “Kentō shimasu”" },
    point: { ja: "① 本当に 考える。② やわらかい ことわり。",
      en: "(1) I'll really think about it. (2) A polite way of saying no.",
      vi: "(1) Sẽ thật sự suy nghĩ. (2) Cách từ chối nhẹ nhàng." },
    why: { ja: "いつまでに 返事を するか 言わない ときは、ことわりの ことが 多いです。仕事では「いつごろ お返事 いただけますか」と 聞いて いいです。",
      en: "If no date for an answer is given, it's often a no. At work, you may ask “When can I expect your answer?”",
      vi: "Nếu không nói khi nào trả lời thì thường là từ chối. Trong công việc có thể hỏi “Khi nào anh/chị có thể trả lời ạ?”" },
    q: { ja: "お客様に 新しい 商品を すすめたら「考えておきます」と 言われました。いちばん 多い 意味は どれですか。",
      choices: ["すぐ 買う", "たぶん 買わない", "明日 買う"], answer: 1 } },
  { id: "w-matakondo", cat: "words",
    title: { ja: "「また 今度」", en: "“Mata kondo”", vi: "“Mata kondo”" },
    point: { ja: "① 次の 機会に 本当に する。② やわらかい ことわり。",
      en: "(1) Let's really do it next time. (2) A soft refusal.",
      vi: "(1) Lần sau sẽ làm thật. (2) Lời từ chối nhẹ nhàng." },
    why: { ja: "日にちを 決めない「また 今度」は、約束では ない ことが 多いです。",
      en: "“Mata kondo” without a set date is usually not a real promise.",
      vi: "“Mata kondo” mà không hẹn ngày cụ thể thường không phải là lời hứa thật." },
    q: { ja: "「今度の 日曜日、遊びに 行こう」と さそったら「また 今度 ね」と 言われました。どういう 意味ですか。",
      choices: ["日曜日に 行く", "今回は 行かない", "来週の 日曜日に 行く"], answer: 1 } },
  { id: "w-doumo", cat: "words",
    title: { ja: "「どうも」", en: "“Dōmo”", vi: "“Dōmo”" },
    point: { ja: "ありがとう・すみません・こんにちは の どれにも 使います。",
      en: "Used for “thank you”, “sorry” and “hello”.",
      vi: "Dùng cho cả “cảm ơn”, “xin lỗi” và “xin chào”." },
    why: { ja: "目上の 人には「どうも」だけで なく「どうも ありがとうございます」と 最後まで 言うと ていねいです。",
      en: "To seniors, say the full phrase, like “Dōmo arigatō gozaimasu”, to be polite.",
      vi: "Với người trên, nói đầy đủ như “Dōmo arigatō gozaimasu” thì lịch sự hơn." },
    q: { ja: "上司に 手伝って もらいました。いちばん ていねいなのは どれですか。",
      choices: ["どうも", "どうも ありがとうございます", "サンキュー"], answer: 1 } },
  { id: "w-tekitou", cat: "words",
    title: { ja: "「適当に」", en: "“Tekitō ni”", vi: "“Tekitō ni”" },
    point: { ja: "① ちょうど いいように（自分で 考えて）。② いいかげんに（悪い 意味）。",
      en: "(1) As you see fit (use your judgment). (2) Carelessly (negative).",
      vi: "(1) Sao cho phù hợp (tự suy nghĩ). (2) Qua loa, cẩu thả (nghĩa xấu)." },
    why: { ja: "上司の「適当に 並べて おいて」は、「あなたが 考えて ちょうど いいように」の 意味です。いいかげんに やっては いけません。",
      en: "When your boss says “Tekitō ni narabete oite”, it means “arrange them sensibly as you see fit”, not carelessly.",
      vi: "Khi cấp trên nói “Tekitō ni narabete oite” là “hãy tự sắp xếp cho hợp lý”, không phải làm qua loa." },
    q: { ja: "上司に「この 商品、適当に 並べて おいて」と 言われました。どう しますか。",
      choices: ["どこでも いいので 置く", "見やすく、ちょうど いいように 並べる", "並べないで おく"], answer: 1 } },
  { id: "w-hai", cat: "words",
    title: { ja: "あいづちの「はい」", en: "“Hai” as a listening sound", vi: "“Hai” khi nghe" },
    point: { ja: "① はい（賛成・わかった）。② 聞いて います（あいづち）。",
      en: "(1) Yes (agree / understood). (2) I'm listening (a back-channel sound).",
      vi: "(1) Vâng (đồng ý / hiểu rồi). (2) Tôi đang nghe (lời đệm khi nghe)." },
    why: { ja: "話の 途中の「はい、はい」は「聞いて います」の 合図で、賛成とは かぎりません。大事な ことは 最後に「わかりました」と はっきり 言います。",
      en: "“Hai, hai” in the middle of a talk just means “I'm listening”, not necessarily “I agree”. For important things, clearly say “Wakarimashita” at the end.",
      vi: "“Hai, hai” giữa câu chuyện chỉ có nghĩa là “tôi đang nghe”, không nhất thiết là đồng ý. Việc quan trọng thì cuối cùng hãy nói rõ “Wakarimashita”." },
    q: { ja: "お客様が 話の 途中で「はい、はい」と 言って います。どういう 意味ですか。",
      choices: ["すべてに 賛成して いる", "話を 聞いて いる", "もう 話を やめて ほしい"], answer: 1 } },
  { id: "w-ichiou", cat: "words",
    title: { ja: "「一応」", en: "“Ichiō”", vi: "“Ichiō”" },
    point: { ja: "① 念の ため。② だいたい できた（完全では ない かも しれない）。",
      en: "(1) Just in case. (2) More or less done (maybe not perfect).",
      vi: "(1) Để cho chắc. (2) Đại khái xong rồi (có thể chưa hoàn hảo)." },
    why: { ja: "「一応 できました」と 言われたら、確認が 必要か 聞きます。自分が 言う ときも、心配な ところを いっしょに 伝えます。",
      en: "If someone says “Ichiō dekimashita”, ask whether it needs checking. When you say it, also mention what you are unsure about.",
      vi: "Nếu ai đó nói “Ichiō dekimashita”, hãy hỏi có cần kiểm tra không. Khi bạn nói vậy, hãy nói luôn chỗ còn lo." },
    q: { ja: "同僚が「一応 できました」と 言いました。どういう 意味に 近いですか。",
      choices: ["完ぺきに できた", "だいたい できたが、確認して ほしい", "まだ 始めて いない"], answer: 1 } },
  { id: "w-bimyou", cat: "words",
    title: { ja: "「微妙」", en: "“Bimyō”", vi: "“Bimyō”" },
    point: { ja: "① はっきり しない・小さな ちがい。② あまり よく ない（よく 使う 意味）。",
      en: "(1) Subtle / unclear. (2) Not so good (the common casual meaning).",
      vi: "(1) Tinh tế / khó nói rõ. (2) Không tốt lắm (nghĩa hay dùng)." },
    why: { ja: "「この 味、ちょっと 微妙」は「あまり おいしく ない」の 意味です。",
      en: "“Kono aji, chotto bimyō” means “This doesn't taste very good.”",
      vi: "“Kono aji, chotto bimyō” nghĩa là “Vị này không ngon lắm.”" },
    q: { ja: "店長が 新しい メニューを 食べて「うーん、微妙だね」と 言いました。どういう 意味ですか。",
      choices: ["とても おいしい", "あまり よく ない", "量が 多い"], answer: 1 } },
  { id: "w-yabai", cat: "words",
    title: { ja: "「やばい」", en: "“Yabai”", vi: "“Yabai”" },
    point: { ja: "① あぶない・まずい。② すごく いい（若い 人の 言い方）。",
      en: "(1) Dangerous / bad. (2) Awesome (young people's slang).",
      vi: "(1) Nguy rồi / tệ rồi. (2) Tuyệt quá (tiếng lóng của giới trẻ)." },
    why: { ja: "仕事では 使わない ほうが いいです。顔や 声の ようすで 意味が 変わります。",
      en: "Better not to use it at work. The meaning depends on the face and tone of voice.",
      vi: "Không nên dùng trong công việc. Nghĩa thay đổi theo nét mặt và giọng nói." },
    q: { ja: "先輩が 時計を 見て「やばい、時間が ない！」と 言いました。どういう 意味ですか。",
      choices: ["時間が たくさん ある", "急がないと まずい", "時計が すてきだ"], answer: 1 } },
  { id: "w-iikagen", cat: "words",
    title: { ja: "「いいかげん」", en: "“Iikagen”", vi: "“Iikagen”" },
    point: { ja: "① ちょうど いい（お湯の いい かげん）。② いいかげんな 仕事＝ていねいで ない。③「いいかげんに して」＝もう やめて（おこって いる）。",
      en: "(1) Just right (e.g., bath temperature). (2) “Iikagen na shigoto” = sloppy work. (3) “Iikagen ni shite” = Stop it! (angry).",
      vi: "(1) Vừa phải (như nhiệt độ nước). (2) “Iikagen na shigoto” = làm cẩu thả. (3) “Iikagen ni shite” = Thôi đi! (đang tức giận)." },
    why: { ja: "「いいかげんに して ください」と 言われたら、相手は おこって います。すぐ やめて あやまります。",
      en: "If someone says “Iikagen ni shite kudasai”, they are angry. Stop right away and apologize.",
      vi: "Nếu bị nói “Iikagen ni shite kudasai” là người đó đang giận. Hãy dừng lại ngay và xin lỗi." },
    q: { ja: "となりの 人に「いいかげんに して ください」と 言われました。どう しますか。",
      choices: ["ほめられたので よろこぶ", "すぐ やめて あやまる", "もっと 大きな 声で 話す"], answer: 1 } },
  { id: "w-enryo", cat: "words",
    title: { ja: "「遠慮します」「遠慮して ください」", en: "“Enryo shimasu” / “Enryo shite kudasai”", vi: "“Enryo shimasu” / “Enryo shite kudasai”" },
    point: { ja: "「遠慮します」＝ていねいな ことわり（しません・いりません）。「〜は ご遠慮 ください」＝してはいけません。",
      en: "“Enryo shimasu” = a polite no. “… wa go-enryo kudasai” (on signs) = Please do not ….",
      vi: "“Enryo shimasu” = từ chối lịch sự. “… wa go-enryo kudasai” (trên biển báo) = Xin đừng …." },
    why: { ja: "「おたばこは ご遠慮 ください」は「たばこを すっては いけません」の 意味です。",
      en: "“O-tabako wa go-enryo kudasai” means “No smoking”.",
      vi: "“O-tabako wa go-enryo kudasai” nghĩa là “Không được hút thuốc”." },
    q: { ja: "店に「おたばこは ご遠慮 ください」と 書いて あります。どういう 意味ですか。",
      choices: ["少しなら すって いい", "たばこを すっては いけない", "たばこを 売って いる"], answer: 1 } },
];
